[package]
name = "ble-types"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = { version = "0.9.1", features = ["serde"] }
postcard = "1.1.3"
serde = {version = "1.0.228", default-features = false}
uuid = {version = "1.18.1", default-features=false}
