// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type Id = { _inner: string }

export type Info = { id: Id; first_name: string; last_name: string }

const ARGS_MAP = { '':'{"get_user":["id"],"hello_world":[]}' }
export type Router = { "": {get_user: (id: Id) => Promise<Info>, 
hello_world: () => Promise<string>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
